name: Feature Request

description: Suggest an idea for this project.

title: "[Feature]: "

labels: [ "Feature", "Components" ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe how you think this feature should work."
      placeholder: "Implement a toggle to switch between light and dark themes."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any additional context, screenshots, or references related to your feature request."
      placeholder: "Links to relevant issues, prior discussions, etc."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/SavouryGin/chop-logic-components/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
