export interface ChopLogicTheme {
  // Colors
  fontColorBase: string;
  fontColorLight: string;
  fontColorAccent: string;
  backgroundColorBase: string;
  backgroundColorLight: string;
  backgroundColorAccent: string;
  backgroundColorTransparent: string;
  borderColorBase: string;
  borderColorLight: string;
  borderColorAccent: string;
  // Gradients
  gradientShadow: string;
  gradientAccent: string;
  gradientTint: string;
  // Fonts
  fontFamilyCore: string;
  fontFamilyMonospace: string;
  fontFamilyFancy: string;
  fontSizeBase: string;
  fontSizeSmall: string;
  fontSizeHeader: string;
  // Units
  gapSmall: string;
  gapMedium: string;
  gapBig: string;
  iconSize: string;
  blockBorderRadius: string;
  // Shadows
  boxShadow: string;
  textShadow: string;
  insetShadow: string;
  // Borders
  borderBase: string;
  borderLight: string;
  borderAccent: string;
  borderOutline: string;
  // Z-indexes
  zIndexBase: string;
  zIndexPopup: string;
  zIndexModal: string;
}
