export enum CLIcon {
  ArrowDown = 'arrow-down',
  ArrowUp = 'arrow-up',
  Back = 'back',
  Cancel = 'cancel',
  CheckboxChecked = 'checkbox-checked',
  CheckboxUnchecked = 'checkbox-unchecked',
  CheckMark = 'check-mark',
  Copy = 'copy',
  Cut = 'cut',
  Delete = 'delete',
  Download = 'download',
  Error = 'error',
  Forward = 'forward',
  Help = 'help',
  Info = 'info',
  Paste = 'paste',
  Question = 'question',
  Save = 'save',
  Upload = 'upload',
  Warning = 'warning',
}
