import { GridColumn, GridFilterCondition, GridFilterState, GridSortState } from '../../../../types';
import { FC } from '../../../../../node_modules/react';
type GridHeadProps = {
    columns: GridColumn[];
    gridId: string;
    selectable: boolean;
    isAllSelected: boolean;
    isAllCheckboxDisabled?: boolean;
    selectAll: () => void;
    deselectAll: () => void;
    sortableByDefault: boolean;
    sortState: GridSortState;
    onSortClick: (field: string) => void;
    filterableByDefault: boolean;
    filterState: GridFilterState;
    onApplyFilter: (field: string, condition: GridFilterCondition) => void;
    onClearFilter: (field: string) => void;
};
export declare const isFilterable: (column: GridColumn, filterableByDefault: boolean) => boolean;
export declare const GridHead: FC<GridHeadProps>;
export {};
